### ISSUE TITLE
Fix tests on CI

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/etcher-homepage#140]
Currently the tests are failing on Travis CI with

```
$ npm run test
> etcher.io@1.1.6 test /home/travis/build/resin-io/etcher-homepage
> ENV=test node ./test/index.js
Listening on port: 1337
Launching Chrome
{ Error: connect ECONNREFUSED 127.0.0.1:42778
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 42778 }
events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by lurch** [comment]
Maybe related to #116 and #127 ? :man_shrugging:

**Comment by thundron** [comment]
Fixed in https://github.com/resin-io/etcher-homepage/pull/142
